services:
  mobile-gitlab:
    image: gitlab/gitlab-ce:16.11.6-ce.0
    ports:
      - '8082:80'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'